#!/bin/sh

# create the mesh
foamCleanPolyMesh
blockMesh

# Change empty patches to wall/emptyy so snappy processes them correctly
sed -i -e 's/empty/emptyy/g' constant/polyMesh/boundary

# Decompose for parallel meshing
decomposePar

# Run snappyHexMesh in parallel
mpirun --use-hwthread-cpus -np 16 snappyHexMesh -parallel -overwrite

# Reconstruct mesh and clean processor directories
reconstructParMesh -constant
rm -rf processor*

# Revert emptyy patches back to empty
sed -i -e 's/emptyy/empty/g' constant/polyMesh/boundary

# Extrude the mesh
extrudeMesh

# create the initial time folder
cp -r 0_org 0

# Decompose the case in order to run in parallel (on 16 cores)
decomposePar

# Run sedFoam in parallel
mpirun --use-hwthread-cpus -np 16 sedFoam_rbgh -parallel > log &
